config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    collection do
      get 'search'
    end
  end




  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  get 'users/profile', to: 'users#profile'
  post 'users/profile', to: 'users#profile'
  patch 'users/update', to:'users#update'
  get 'users/profile/edit', to: 'users#edit'
  get 'users/show'
  resources :users

  post 'reservations/confirm', to: 'reservations#confirm'
  get 'reservations', to: 'reservations#index'


  resources :reservations 


  devise_scope :user do

  end
  

  root 'plans#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :image

  has_many :rooms
  has_many :reservations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
   #def edit
    #@user = current_user
    #if @user.update(params.permit(:name, :introduction, :image))
      #flash[:notice] = "Profile was successfully updated."
      #redirect_to users_show_path
    #else
      #render :edit
    #end
   #end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    users_show_path(current_user.id)
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
    new_user_registration_path
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :show]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    #binding.pry
    if @user.update(params.require(:user).permit(:name, :introduction, :image))
      flash[:notice] = "ユーザーの情報を更新しました"
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  def profile
    @user = current_user
  end

  private
  def user_params
    params.permit(:name, :email, :password, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>

        <%= form_with model: @user, url: users_profile_path, id: 'new_user', class: 'new_user', local: true do |f| %>
        
        <div class="field">
        <div class="form-group">
          <%= f.label :ユーザー名 %><br />
          <%= f.text_field :name, class:"form-control", placeholder: "ユーザー名を入力" %>
        </div>
      </div>

      <div class="field">
        <div class="form-group">
          <label class="col-md-3" for="name">アイコン画像</label>
             <% if @user.image.attached? %>
              <%= image_tag @user.image,class:"icon-image host-icon"%> 
             <% else %>
              <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png"  alt='アイコン画像' class="icon-image host-icon">
             <% end %> 
          <%= f.file_field :image, class:"btn btn-primary", placeholder: "アイコン画像をアップロード" %>
        </div>
      </div>

      <div class="field">
        <div class="form-group">
          <%= f.label :introduction, "自己紹介" %><br />
          <%= f.text_area :introduction, class:"form-control", placeholder: "自己紹介文入力してください" %>
        </div>
      </div>
      <div class="update-content">
        <div class="row">
            <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
        </div>
      </div>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント", users_show_path %>
        </li>

        <li class="">
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

   <h3>プロフィール</h3>
   <div class="user-view-box">
      
    <%= form_with model: @user, local: true do |f| %>

     <div class="update-content">
      <div class="field">
        <div class="form-group user-name">
          <%= f.label :name, "ユーザー名" %><br />
          <div class="col-md-9"><%= @user.name %></div>
        </div>
      </div>
     </div>

      <div class="update-content">
        <div class="col-md-6">
         <div class="row">
          <div class="icon-box">
           <div class="col-md-9">
            <label class="profile-image" for="name">プロフィール画像</label><br />
             <% if @user.image.attached? %>
              <%= image_tag @user.image,class:"icon-image host-icon"%> 
             <% else %>
              <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png"  alt='アイコン画像' class="icon-image host-icon">
             <% end %> 
           </div>
          </div>
         </div>
        </div>
      </div>

      <div class="update-content">
        <div class="row user-introduction">
          <%= f.label :introduction, "自己紹介" %><br />
          <div class="col-md-9"><%= @user.introduction %></div>
        </div>
      </div>

      <div class="update-content">
        <div class="row">
          <%= link_to "編集", users_profile_edit_path, class:"col-md-2 btn btn-primary mx-3"%>
        </div>
      </div>

    <% end %>

   </div>
  </div>
</div>

app/views/users/profile_edit.html.erb
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>

        <%= form_with model: @user, url: user_profile_path, id: 'new_user', class: 'new_user', local: true do |f| %>
        
        <div class="field">
        <div class="form-group">
          <%= f.label :ユーザー名 %><br />
          <%= f.text_field :name, class:"form-control", placeholder: "ユーザー名を入力" %>
        </div>
      </div>

      <div class="field">
        <div class="form-group">
          <%= f.label :icon_image, "アイコン画像" %><br />
          <%= f.text_field :image, class:"icon-image host-icon", placeholder: "アイコン画像をアップロード" %>
        </div>
      </div>

      <div class="field">
        <div class="form-group">
          <%= f.label :introduction, "自己紹介" %><br />
          <%= f.text_area :introduction, class:"form-control", placeholder: "自己紹介文入力してください" %>
        </div>
      </div>
      <div class="update-content">
        <div class="row">
            <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
        </div>
      </div>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント", users_show_path %>
        </li>

        <li class="">
          <%= link_to "プロフィール", users_profile_path %>
        </li>
      </ul>
    </div>

    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        
        <%= form_with model: @user, url: user_registration_path, id: 'new_user', class: 'new_user', local: true do |f| %>

        <div class="update-content">
          <div class="row">
            <%= f.label :メールアドレス,class:"col-md-3" %><br />
            <div class="col-md-9"><%= @user.email %></div>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <%= f.label :パスワード,class:"col-md-3" %><br />
            <div class="col-md-9">********</div>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <%= link_to "編集", edit_user_registration_path, class:"col-md-2 btn btn-primary mx-3"%>
          </div>
        </div>


       <% end %>

      </div>
    </div>
  </div>
</div>