config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    collection do
      get 'search'
    end
  end




  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  get 'users/profile', to: 'users#profile'
  post 'users/profile', to: 'users#profile'
  patch 'users/update', to:'users#update'
  get 'users/profile/edit', to: 'users#edit'
  get 'users/show'
  resources :users

  post 'reservations/confirm', to: 'reservations#confirm'
  get 'reservations', to: 'reservations#index'


  resources :reservations 


  devise_scope :user do

  end
  

  root 'plans#index'

end

app/models/room.rb
class Room < ApplicationRecord

      has_one_attached :picture
      has_many :reservations
      belongs_to :user

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms or /rooms.json
  def index
    @user = current_user
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @user = current_user
		@room = Room.find(params[:id]) 
		@reservation = Reservation.new
  end

  # GET /rooms/new
  def new
    @user = current_user
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @user = current_user
    @room = Room.new(room_params)
      if @room.save
        redirect_to :rooms ,notice: "ルーム情報を新規登録しました"
      else
        flash[:alert] = "ルーム情報を登録できませんでした"
        render "new"
      end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
     @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :introduction, :single_rate, :address, :picture, :user_id, :room_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <div class="room-register">
    <table>
       <thead>
          <tr algin="center">
              <th>ルーム画像</th>
              <th>ルーム名</th>
              <th>ルーム紹介</th>
              <th>料金</th>
              <th>作成日</th>
          </tr>
       </thead>
       <tbody>
           <% @rooms.each do |room| %>
              <tr>
                 <td>
                     <% if room.picture.attached? %>
                       <%= image_tag room.picture,class:"room-register-image"%> 
                     <% else %>
                       <%= image_tag 'room2.png', class: "room-register-image" %>
                     <% end %>
                  </td>
                 <td class="register-text"><%= link_to room.name, {controller: 'rooms', action: 'show', id: room.id} %></td>
                 <td><%= room.introduction %></td>
                 <td><%= room.single_rate %></td>
                 <td><%= room.created_at.strftime('%Y/%m/%d %H:%M:%S')  %></td>
              </tr>
           <% end %>
       </tbody>
    </table>
  </div> 
</div>





 

app/views/rooms/new.html.erb
<div class="container-fiuld room-new">
   <div class="row">
      <div class="col-md-10 room-view">
         <div class="room-view-box">
            <%= form_with model: @room do |f| %>

            <%= f.hidden_field :user_id, :value => @user.id %>

            <div class="update-content">
               <div class="row">
                  <h5>ルーム情報登録</h5>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.label :name,"ルーム名", class:"col-md-3 required-a" %>
                  <%= f.text_field :name, placeholder:"ルーム名を入力", class:"form-control col-md-9 mb-4 field_wieth_error" %>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.label :introduction,"ルーム紹介", class:"col-md-3 required-a" %>
                  <%= f.text_field :introduction, placeholder:"ルーム紹介を入力", class:"form-control col-md-9 mb-4 field_wieth_error" %>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.label :single_rate,"料金", class:"col-md-3 required-a" %>
                  <%= f.number_field :single_rate, placeholder:"一日あたりの料金を入力", class:"form-control mb-4 col-md-9 field_wieth_error" %>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.label :address,"住所", class:"col-md-3 required-a" %>
                  <%= f.text_field :address,placeholder:"住所を入力", class:"form-control mb-4 col-md-9 field_wieth_error" %>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.label :picture,"ルーム画像", class:"col-md-3 required-a" %>
                  <%= f.file_field :picture, class:"mb-4 col-md-9 field_wieth_error" %>
               </div>
            </div>

            <div class="update-content">
               <div class="row">
                  <%= f.submit "登録" , class:"col-md-2 btn btn-primary mx-3"%>
               </div>
            </div>

            <% end %>

         </div>
      </div>
   </div>
</div>

app/views/rooms/search.html.erb
<div class="container-fluid room">
  <h4 class="pb-4">検索結果:<%= @results.count %>件</h4>
      <div class="room-posts">
         <% @results.each do |room| %>
           <div class="room-box">
              <p>
                <% if room.picture.attached? %>
                  <%= image_tag room.picture,class:"room-posts-image"%> 
                <% else %>
                  <%= image_tag 'room2.png', class: "room-posts-image" %>
                <% end %>
              </p>
              <p class="posts-name"><%= link_to room.name, {controller: 'reservations', action: 'new', id: room.id} %></p>
              <p class="posts-content"><%= room.address %></p>
              <p class="price-icon"><%= room.single_rate %></p>
           </div>
         <% end %>
      </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <%= render "devise/shared/error_messages", obj: @reservation %>
   <div class="row">
      <div class="col-md-8">
          <% if @room.picture.attached? %>
            <%= image_tag @room.picture,class:"room-show-image"%> 
          <% else %>
            <%= image_tag 'room2.png', class: "room-show-image" %>
          <% end %>
          <div class="room-show-detile mt-5">
             <div class="room-show-detile-icon">
                 <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" class="host-icon">
             </div>

             <div class="room-show-profile ml-4">
                <p class="room-show-profile-name"><%= @room.name %></p>
                <p class="room-show-profile-address"><%= @room.address %></p>
             </div>
          </div>

          <p class="room-show-detile-content"><%= @room.introduction %></p>
      </div>

      <div class="col-md-4">
          <div class="room-show-nav">
              <%= form_with model: @reservation, url: reservations_confirm_path, local: true do |f| %>
              <h5 class="price-icon">¥<%= @room.single_rate %> / 日</h5>

                 <div class="room-show-date-select">
                    <div>                    
                     <%= f.label :start_date, "開始日" %>
                     <%= f.date_field :start_date, class:"form-control mb-4" %>
                    </div>
                    <div>
                     <%= f.label :end_date, "終了日" %>
                     <%= f.date_field :end_date, class:"form-control mb-4" %>
                    </div>
                    <div>
                     <%= f.label :people, "人数" %>
                     <%= f.number_field :people, class:"form-control mb-4" %>
                    </div>
                     <%= f.hidden_field :room_id, value: @room.id %>
                     <%= f.hidden_field :user_id, value: @user.id %>
                     <%= f.submit "予約する", class:"form-control mb-4" %>
                 </div>
              <% end %>
          </div>
      </div>
   </div>
</div>