config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    collection do
      get 'search'
    end
  end




  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  get 'users/profile', to: 'users#profile'
  post 'users/profile', to: 'users#profile'
  patch 'users/update', to:'users#update'
  get 'users/profile/edit', to: 'users#edit'
  get 'users/show'
  resources :users

  post 'reservations/confirm', to: 'reservations#confirm'
  get 'reservations', to: 'reservations#index'


  resources :reservations 


  devise_scope :user do

  end
  

  root 'plans#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <title>TaskApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <header class="header">
   <div class="header-inner">
    <div class="header-left-nav">
      <%= link_to image_tag('https://rails-02-sample.herokuapp.com/assets/common/logo.png', width: '221px'), 'http://localhost:3000/', class: 'logo' %>
         <div class="header-sharch d-lg-inline-block d-none">
           <%= search_form_for @q, url: search_rooms_path do |f| %>
              <%= f.search_field :address_cont, placeholder:"エリア", class: "form-control" %> 
              <i class="fas fa-map-marker-alt"></i>
           <% end %>
         </div>

         <div class="header-sharch d-lg-inline-block d-none">
           <%= search_form_for @q, url: search_rooms_path do |f| %>
              <%= f.search_field :name_or_introduction_or_address_cont, placeholder:"キーワード", class: "form-control" %> 
              <i class="fas fa-search"></i>
           <% end %>
         </div>
     </div>

     <div class="header-rignt-nav">
       <div class="nav-item">
      <% if user_signed_in? %>
        <div class="nav-item d-sm-inline-block d-none">
         <%= current_user.name %>
        </div>
        <div class="nav-item">
          <% if current_user.image.attached? %>
           <%= image_tag current_user.image, class: "host-icon nav-trigger" %>
          <% else %>
            <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png"  alt='アイコン画像' class="mx-3 p-1 host-icon nav-trigger">
          <% end %>
          <ul class="header-nav-menu" >
            <li class="menu_li"><%= link_to "ルーム登録", new_room_path %></li>
            <li class="menu_li"><%= link_to "予約済みルーム一覧", reservations_path %></li>
            <li class="menu_li"><%= link_to "登録済みルーム一覧",rooms_path%></li>
            <li class="menu_li"><%= link_to "設定", users_show_path %></li>
            <li class="menu_li"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      <% else %>
         <%= link_to "ログイン", new_user_session_path, class: "user btn-primary my-2 mx-3 " %>
         <%= link_to "新規登録", new_user_registration_path, class: "user btn-secondary" %>
      <% end %>
       <script>
         $(function(){
           $('.nav-trigger').click(function() {
            $('.header-nav-menu').slideToggle();
           });
         });
       </script>
       <div class="notifications"></div>
      </div>
     </div>
    </div>
   </div>
  </header>

  <body>
    
    <div class="clearfix">
      <%= notice %>
      <%= alert %>
    </div>
    <%= yield %>

    <footer class="footer">
       <p>© 2020 POTEPAN.INC.</p>
    </footer>

    
  </body>
</html>